"""Kairos Agent — SQLAlchemy ORM Models.

Maps to the database schema defined in Section 10 of the implementation document.
All tables use UUID primary keys and support multi-pipeline operation.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """SQLAlchemy declarative base for all models."""


class PipelineRun(Base):
    """Top-level pipeline execution record."""

    __tablename__ = "pipeline_runs"

    pipeline_run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    pipeline: Mapped[str] = mapped_column(String(50), nullable=False)
    idea_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    simulation_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    output_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    status: Mapped[str] = mapped_column(String(50), default="running")
    started_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    completed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    total_cost_usd: Mapped[float | None] = mapped_column(Numeric(8, 4), nullable=True)
    total_duration_sec: Mapped[int | None] = mapped_column(Integer, nullable=True)

    __table_args__ = (
        Index("idx_pipeline_runs_status", "pipeline", "status"),
        Index("idx_pipeline_runs_started", started_at.desc()),
    )

    # Relationships (Finding 2.4)
    ideas: Mapped[list["VideoIdea"]] = relationship(back_populates="pipeline_run", cascade="all, delete-orphan")
    simulations: Mapped[list["Simulation"]] = relationship(back_populates="pipeline_run", cascade="all, delete-orphan")
    outputs: Mapped[list["Output"]] = relationship(back_populates="pipeline_run", cascade="all, delete-orphan")
    agent_runs: Mapped[list["AgentRun"]] = relationship(back_populates="pipeline_run", cascade="all, delete-orphan")


class VideoIdea(Base):
    """Ideas / concepts generated by the Idea Agent."""

    __tablename__ = "video_ideas"

    idea_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    pipeline_run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("pipeline_runs.pipeline_run_id", ondelete="CASCADE"),
        nullable=False,
    )
    pipeline: Mapped[str] = mapped_column(String(50), nullable=False)
    concept: Mapped[dict] = mapped_column(JSONB, nullable=False)  # type: ignore[type-arg]
    category: Mapped[str | None] = mapped_column(String(100), nullable=True)
    novelty_score: Mapped[float | None] = mapped_column(Numeric(3, 1), nullable=True)
    feasibility_score: Mapped[float | None] = mapped_column(Numeric(3, 1), nullable=True)
    status: Mapped[str] = mapped_column(String(50), default="pending")
    performance_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (
        Index("idx_ideas_pipeline_status", "pipeline", "status"),
        Index("idx_ideas_category", "pipeline", "category", created_at.desc()),
    )

    pipeline_run: Mapped["PipelineRun"] = relationship(back_populates="ideas")


class CategoryStat(Base):
    """Category rotation cache (materialised, not source of truth)."""

    __tablename__ = "category_stats"

    pipeline: Mapped[str] = mapped_column(String(50), primary_key=True)
    category: Mapped[str] = mapped_column(String(100), primary_key=True)
    total_count: Mapped[int] = mapped_column(Integer, default=0)
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    avg_performance: Mapped[float | None] = mapped_column(Numeric(5, 2), nullable=True)
    streak_count: Mapped[int] = mapped_column(Integer, default=0)
    videos_last_30_days: Mapped[int] = mapped_column(Integer, default=0)
    # Accumulated category-level knowledge (AI review §6)
    knowledge: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]

    __table_args__ = (Index("idx_category_stats_pipeline", "pipeline"),)


class Simulation(Base):
    """Simulation execution records."""

    __tablename__ = "simulations"

    simulation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    idea_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("video_ideas.idea_id", ondelete="CASCADE"),
        nullable=False,
    )
    pipeline_run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("pipeline_runs.pipeline_run_id", ondelete="CASCADE"),
        nullable=False,
    )
    pipeline: Mapped[str] = mapped_column(String(50), nullable=False)
    code_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    raw_video_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    frame_contact_sheet: Mapped[str | None] = mapped_column(Text, nullable=True)
    stats: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]
    scene_metadata: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]
    validation_passed: Mapped[bool] = mapped_column(Boolean, default=False)
    iteration_count: Mapped[int] = mapped_column(Integer, default=0)
    iteration_history: Mapped[list] = mapped_column(JSONB, default=list)  # type: ignore[type-arg]
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (Index("idx_simulations_pipeline", "pipeline", created_at.desc()),)

    pipeline_run: Mapped["PipelineRun"] = relationship(back_populates="simulations")


class Output(Base):
    """Final assembled videos."""

    __tablename__ = "outputs"

    output_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    simulation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("simulations.simulation_id", ondelete="CASCADE"),
        nullable=False,
    )
    pipeline_run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("pipeline_runs.pipeline_run_id", ondelete="CASCADE"),
        nullable=False,
    )
    final_video_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    captions: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]
    music_track: Mapped[str | None] = mapped_column(Text, nullable=True)
    music_metadata: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(50), default="pending_review")
    review_action: Mapped[str | None] = mapped_column(String(50), nullable=True)
    review_feedback: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    cost_usd: Mapped[float | None] = mapped_column(Numeric(6, 4), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (Index("idx_outputs_status", "status"),)

    pipeline_run: Mapped["PipelineRun"] = relationship(back_populates="outputs")


class PublishQueue(Base):
    """Publishing queue — decouples production from distribution."""

    __tablename__ = "publish_queue"

    queue_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    output_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("outputs.output_id", ondelete="CASCADE"),
        nullable=False,
    )
    platform: Mapped[str] = mapped_column(String(50), nullable=False)
    account: Mapped[str | None] = mapped_column(String(100), nullable=True)
    scheduled_for: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    platform_title: Mapped[str | None] = mapped_column(Text, nullable=True)
    platform_description: Mapped[str | None] = mapped_column(Text, nullable=True)
    platform_tags: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]
    status: Mapped[str] = mapped_column(String(50), default="queued")
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (Index("idx_publish_queue_status", "status", "scheduled_for"),)


class PublishLog(Base):
    """Publish log — records after successful upload."""

    __tablename__ = "publish_log"

    publish_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    output_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("outputs.output_id", ondelete="CASCADE"),
        nullable=False,
    )
    queue_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("publish_queue.queue_id", ondelete="CASCADE"),
        nullable=False,
    )
    platform: Mapped[str] = mapped_column(String(50), nullable=False)
    account: Mapped[str | None] = mapped_column(String(100), nullable=True)
    platform_video_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    published_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    views_7d: Mapped[int | None] = mapped_column(Integer, nullable=True)
    views_30d: Mapped[int | None] = mapped_column(Integer, nullable=True)
    likes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    comments: Mapped[int | None] = mapped_column(Integer, nullable=True)
    shares: Mapped[int | None] = mapped_column(Integer, nullable=True)
    avg_view_duration_sec: Mapped[float | None] = mapped_column(Numeric(6, 2), nullable=True)
    retention_rate: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    revenue_usd: Mapped[float | None] = mapped_column(Numeric(8, 4), nullable=True)

    __table_args__ = (Index("idx_publish_log_platform", "platform", published_at.desc()),)


class AgentRun(Base):
    """Agent execution log — every LLM call and significant operation."""

    __tablename__ = "agent_runs"

    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    pipeline_run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("pipeline_runs.pipeline_run_id", ondelete="CASCADE"),
        nullable=False,
    )
    idea_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    agent_name: Mapped[str] = mapped_column(String(100), nullable=False)
    step_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    attempt_number: Mapped[int | None] = mapped_column(Integer, nullable=True, default=1)
    model_used: Mapped[str | None] = mapped_column(String(100), nullable=True)
    input_summary: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]
    output_summary: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # type: ignore[type-arg]
    tokens_in: Mapped[int | None] = mapped_column(Integer, nullable=True)
    tokens_out: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cost_usd: Mapped[float | None] = mapped_column(Numeric(8, 6), nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    status: Mapped[str | None] = mapped_column(String(50), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    thinking_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (
        Index("idx_agent_runs_pipeline", "pipeline_run_id"),
        Index("idx_agent_runs_model", "model_used", created_at.desc()),
    )

    pipeline_run: Mapped["PipelineRun"] = relationship(back_populates="agent_runs")


class TrainingExample(Base):
    """Training examples for few-shot learning and fine-tuning.

    Populated automatically after successful pipeline runs.
    The ``verified`` flag is the final gate — examples are NOT injected
    into prompts until ``verified=True``.  This lets the system accumulate
    data safely while operators decide when to "go live".
    """

    __tablename__ = "training_examples"

    example_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    simulation_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    pipeline: Mapped[str] = mapped_column(String(50), nullable=False)
    category: Mapped[str | None] = mapped_column(String(100), nullable=True)
    concept_brief: Mapped[dict] = mapped_column(JSONB, nullable=False)  # type: ignore[type-arg]
    simulation_code: Mapped[str] = mapped_column(Text, nullable=False)
    reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    thinking_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    validation_passed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    human_approved: Mapped[bool] = mapped_column(Boolean, nullable=False)
    verified: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    iteration_count: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    rejection_reason: Mapped[str | None] = mapped_column(String(50), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (
        Index("idx_training_approved", "pipeline", "human_approved", "validation_passed"),
        Index("idx_training_verified", "pipeline", "category", "verified"),
    )


class PipelineConfig(Base):
    """Pipeline configuration — per-pipeline defaults."""

    __tablename__ = "pipeline_config"

    pipeline: Mapped[str] = mapped_column(String(50), primary_key=True)
    engine: Mapped[str] = mapped_column(String(100), nullable=False)
    target_duration_min: Mapped[int] = mapped_column(Integer, default=62)
    target_duration_max: Mapped[int] = mapped_column(Integer, default=68)
    target_fps: Mapped[int] = mapped_column(Integer, default=30)
    target_resolution: Mapped[str] = mapped_column(String(20), default="1080x1920")
    max_iterations: Mapped[int] = mapped_column(Integer, default=5)
    categories: Mapped[list] = mapped_column(JSONB, nullable=False)  # type: ignore[type-arg]
    active: Mapped[bool] = mapped_column(Boolean, default=True)
    config: Mapped[dict] = mapped_column(JSONB, default=dict)  # type: ignore[type-arg]
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
