-- Kairos Agent — Initial Database Schema
-- Migration: 001_initial_schema.sql
-- Matches Section 10 of the implementation document.
-- Run against PostgreSQL 16.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- pipeline_runs — Top-level pipeline execution record
-- ============================================================================
CREATE TABLE pipeline_runs (
    pipeline_run_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    pipeline        VARCHAR(50)   NOT NULL,
    idea_id         UUID,
    simulation_id   UUID,
    output_id       UUID,
    status          VARCHAR(50)   DEFAULT 'running',
    started_at      TIMESTAMPTZ   DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    total_cost_usd  NUMERIC(8,4),
    total_duration_sec INTEGER
);

CREATE INDEX idx_pipeline_runs_status  ON pipeline_runs (pipeline, status);
CREATE INDEX idx_pipeline_runs_started ON pipeline_runs (started_at DESC);

-- ============================================================================
-- video_ideas — Ideas / concepts generated by the Idea Agent
-- ============================================================================
CREATE TABLE video_ideas (
    idea_id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    pipeline_run_id  UUID         NOT NULL REFERENCES pipeline_runs(pipeline_run_id),
    pipeline         VARCHAR(50)  NOT NULL,
    concept          JSONB        NOT NULL,
    category         VARCHAR(100),
    novelty_score    NUMERIC(3,1),
    feasibility_score NUMERIC(3,1),
    status           VARCHAR(50)  DEFAULT 'pending',
    performance_data JSONB,
    created_at       TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_ideas_pipeline_status ON video_ideas (pipeline, status);
CREATE INDEX idx_ideas_category        ON video_ideas (pipeline, category, created_at DESC);

-- ============================================================================
-- category_stats — Category rotation cache (materialised, not source of truth)
-- ============================================================================
CREATE TABLE category_stats (
    pipeline          VARCHAR(50)  NOT NULL,
    category          VARCHAR(100) NOT NULL,
    total_count       INTEGER      DEFAULT 0,
    last_used_at      TIMESTAMPTZ,
    avg_performance   NUMERIC(5,2),
    streak_count      INTEGER      DEFAULT 0,
    videos_last_30_days INTEGER    DEFAULT 0,
    PRIMARY KEY (pipeline, category)
);

CREATE INDEX idx_category_stats_pipeline ON category_stats (pipeline);

-- ============================================================================
-- simulations — Simulation execution records
-- ============================================================================
CREATE TABLE simulations (
    simulation_id     UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    idea_id           UUID         NOT NULL REFERENCES video_ideas(idea_id),
    pipeline_run_id   UUID         NOT NULL REFERENCES pipeline_runs(pipeline_run_id),
    pipeline          VARCHAR(50)  NOT NULL,
    code_path         TEXT,
    raw_video_path    TEXT,
    frame_contact_sheet TEXT,
    stats             JSONB,
    scene_metadata    JSONB,
    validation_passed BOOLEAN      DEFAULT FALSE,
    iteration_count   INTEGER      DEFAULT 0,
    iteration_history JSONB        DEFAULT '[]'::JSONB,
    created_at        TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_simulations_pipeline ON simulations (pipeline, created_at DESC);

-- ============================================================================
-- outputs — Final assembled videos
-- ============================================================================
CREATE TABLE outputs (
    output_id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    simulation_id     UUID         NOT NULL REFERENCES simulations(simulation_id),
    pipeline_run_id   UUID         NOT NULL REFERENCES pipeline_runs(pipeline_run_id),
    final_video_path  TEXT,
    captions          JSONB,
    music_track       TEXT,
    music_metadata    JSONB,
    title             TEXT,
    description       TEXT,
    status            VARCHAR(50)  DEFAULT 'pending_review',
    review_action     VARCHAR(50),
    review_feedback   TEXT,
    reviewed_at       TIMESTAMPTZ,
    cost_usd          NUMERIC(6,4),
    created_at        TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_outputs_status ON outputs (status);

-- ============================================================================
-- publish_queue — Decouples production from distribution
-- ============================================================================
CREATE TABLE publish_queue (
    queue_id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    output_id          UUID         NOT NULL REFERENCES outputs(output_id),
    platform           VARCHAR(50)  NOT NULL,
    account            VARCHAR(100),
    scheduled_for      TIMESTAMPTZ,
    platform_title     TEXT,
    platform_description TEXT,
    platform_tags      JSONB,
    status             VARCHAR(50)  DEFAULT 'queued',
    attempts           INTEGER      DEFAULT 0,
    last_error         TEXT,
    created_at         TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_publish_queue_status ON publish_queue (status, scheduled_for);

-- ============================================================================
-- publish_log — Records after successful upload
-- ============================================================================
CREATE TABLE publish_log (
    publish_id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    output_id          UUID         NOT NULL REFERENCES outputs(output_id),
    queue_id           UUID         NOT NULL REFERENCES publish_queue(queue_id),
    platform           VARCHAR(50)  NOT NULL,
    account            VARCHAR(100),
    platform_video_id  TEXT,
    published_at       TIMESTAMPTZ,
    views_7d           INTEGER,
    views_30d          INTEGER,
    likes              INTEGER,
    comments           INTEGER,
    shares             INTEGER,
    avg_view_duration_sec NUMERIC(6,2),
    retention_rate     NUMERIC(5,4),
    revenue_usd        NUMERIC(8,4)
);

CREATE INDEX idx_publish_log_platform ON publish_log (platform, published_at DESC);

-- ============================================================================
-- agent_runs — Every LLM call and significant operation logged
-- ============================================================================
CREATE TABLE agent_runs (
    run_id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    pipeline_run_id   UUID         NOT NULL REFERENCES pipeline_runs(pipeline_run_id),
    idea_id           UUID,
    agent_name        VARCHAR(100) NOT NULL,
    step_name         VARCHAR(100),
    model_used        VARCHAR(100),
    input_summary     JSONB,
    output_summary    JSONB,
    tokens_in         INTEGER,
    tokens_out        INTEGER,
    cost_usd          NUMERIC(8,6),
    latency_ms        INTEGER,
    status            VARCHAR(50),
    error_message     TEXT,
    created_at        TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_agent_runs_pipeline ON agent_runs (pipeline_run_id);
CREATE INDEX idx_agent_runs_model    ON agent_runs (model_used, created_at DESC);

-- ============================================================================
-- training_examples — For future fine-tuning
-- ============================================================================
CREATE TABLE training_examples (
    example_id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    simulation_id    UUID         NOT NULL REFERENCES simulations(simulation_id),
    pipeline         VARCHAR(50)  NOT NULL,
    concept_brief    JSONB        NOT NULL,
    simulation_code  TEXT         NOT NULL,
    validation_passed BOOLEAN     NOT NULL,
    human_approved   BOOLEAN      NOT NULL,
    rejection_reason VARCHAR(50),
    created_at       TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_training_approved ON training_examples (pipeline, human_approved, validation_passed);

-- ============================================================================
-- pipeline_config — Per-pipeline configuration
-- ============================================================================
CREATE TABLE pipeline_config (
    pipeline           VARCHAR(50)  PRIMARY KEY,
    engine             VARCHAR(100) NOT NULL,
    target_duration_min INTEGER     DEFAULT 62,
    target_duration_max INTEGER     DEFAULT 68,
    target_fps         INTEGER      DEFAULT 30,
    target_resolution  VARCHAR(20)  DEFAULT '1080x1920',
    max_iterations     INTEGER      DEFAULT 5,
    categories         JSONB        NOT NULL,
    active             BOOLEAN      DEFAULT TRUE,
    config             JSONB        DEFAULT '{}'::JSONB,
    created_at         TIMESTAMPTZ  DEFAULT NOW()
);

-- ============================================================================
-- Seed data — Physics pipeline initial config
-- ============================================================================
INSERT INTO pipeline_config (pipeline, engine, categories, config)
VALUES (
    'physics',
    'pygame_pymunk',
    '["ball_pit", "marble_funnel", "domino_chain", "destruction"]'::JSONB,
    '{
        "sandbox_timeout_sec": 300,
        "sandbox_memory": "4g",
        "sandbox_cpus": 2,
        "max_iterations": 5,
        "target_duration_sec": 65,
        "resolution": "1080x1920",
        "fps": 30
    }'::JSONB
);

-- Seed category_stats for physics pipeline
INSERT INTO category_stats (pipeline, category, total_count, videos_last_30_days, streak_count)
VALUES
    ('physics', 'ball_pit', 0, 0, 0),
    ('physics', 'marble_funnel', 0, 0, 0),
    ('physics', 'domino_chain', 0, 0, 0),
    ('physics', 'destruction', 0, 0, 0);
