"""Kairos Agent — Idea Agent Response Models.

Pydantic models used as Instructor response_model for LLM calls
in the Idea Agent pipeline. These define the structured output
schema that LLMs must conform to.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from kairos.models.contracts import (
    AudioBrief,
    EnergyLevel,
    ScenarioCategory,
    SimulationRequirements,
)


class CategorySelection(BaseModel, frozen=True):
    """Structured output from the Category Selector LLM.

    The Category Selector receives category stats and rotation constraints,
    then selects the best category with reasoning.
    """

    selected_category: ScenarioCategory = Field(
        description="The scenario category to use for the next video",
    )
    reasoning: str = Field(
        description="Brief explanation of why this category was selected",
    )


class RankedConcept(BaseModel, frozen=True):
    """A single concept generated by the Concept Developer.

    The Concept Developer generates 3 ranked concepts and returns them
    in order of quality/potential.
    """

    title: str = Field(
        description="Short descriptive title for the concept",
    )
    visual_brief: str = Field(
        description="2-3 sentence description of what the viewer sees",
    )
    simulation_requirements: SimulationRequirements = Field(
        description="Technical requirements for the simulation engine",
    )
    audio_brief: AudioBrief = Field(
        default_factory=lambda: AudioBrief(
            mood=["upbeat"],
            energy_curve=EnergyLevel.BUILDING,
        ),
        description="Audio/music requirements for the video",
    )
    hook_text: str = Field(
        description="Hook caption text (<=6 words) shown at 0-2s",
        max_length=50,
    )
    novelty_score: float = Field(
        ge=0.0,
        le=10.0,
        description="How novel this concept is vs existing content (0-10)",
    )
    feasibility_score: float = Field(
        ge=0.0,
        le=10.0,
        description="How feasible to implement in the simulation engine (0-10)",
    )
    rank_reasoning: str = Field(
        description="Why this concept is ranked at this position",
    )


class ConceptDeveloperResponse(BaseModel, frozen=True):
    """Structured output from the Concept Developer LLM.

    Returns 3 ranked concepts. The pipeline uses the top-ranked one.
    """

    concepts: list[RankedConcept] = Field(
        min_length=1,
        max_length=5,
        description="Ranked list of concepts (best first)",
    )

    @property
    def top_concept(self) -> RankedConcept:
        """Return the highest-ranked concept."""
        return self.concepts[0]


class CategoryReport(BaseModel, frozen=True):
    """Per-category statistics for the Inventory Analyst report."""

    category: str
    total_count: int = 0
    videos_last_30_days: int = 0
    streak_count: int = 0
    percentage_last_30_days: float = Field(
        default=0.0,
        description="Percentage of last 30 days output this category represents",
    )
    is_last_used: bool = False
    needs_boost: bool = Field(
        default=False,
        description="True if category has fewer than 5 total videos",
    )


class InventoryReport(BaseModel, frozen=True):
    """Inventory analysis produced by the Inventory Analyst (programmatic).

    No LLM needed — pure database queries compiled into a structured report.
    """

    pipeline: str = Field(description="Pipeline identifier")
    total_videos: int = Field(description="Total videos produced across all categories")
    categories: list[CategoryReport] = Field(
        description="Per-category breakdown",
    )
    last_category: str | None = Field(
        default=None,
        description="Category of the most recent video (for hard block)",
    )
    recent_categories: list[str] = Field(
        default_factory=list,
        description="Recent category sequence (newest first, for streak detection)",
    )
